### ISSUE TITLE
Tracking issue for kernel tracing

### ISSUE THREAD

**Issue by hyyking** [hyyking/kernel#10]
# Goal

Implement a nice logging infrastructure for the kernel AND the bootloader (so no allocations allowed). Looking at logs anyone should be able to (non-exhaustive):

- Follow page allocation/deallocation in a precise or grouped up view
- See fundamental modification operations (GDT/IDT/APIC)
- Follow task scheduling
- Follow system calls
- Follow drive operations
- Be able to debug most parts of the kernel

## Tasks

- [ ] add logging to the bootloader #7
- [ ] send structured logs to the console #8 
- [ ] replace log with tracing #9
- [ ] page allocation/deallocation
  - [ ] tracing in page_mapper
  - [ ] use spans for operations
  - [ ] support folding over many page allocations in `konsole`
- [ ] fundamental modifications:
  - [ ] GDT
  - [ ] IDT
  - [ ] APIC (when supported)
- [ ] system calls (when supported)
- [ ] drive operations (when supported)
- [ ] scheduler (when supported)
- [ ] debuging
  - [ ]  dbg! like macro
